<?php
require_once 'Configuration/General.php';
require_once 'Configuration/Startup.php';
require_once 'Configuration/Action.php';
require_once 'Configuration/Session.php';
require_once 'Configuration/Cookie.php';
require_once 'Configuration/Database.php';
require_once 'Configuration/Limit.php';
require_once 'Configuration/Notification.php';
require_once 'Configuration/Expiry.php';
require_once 'Library/Controller.php';
require_once 'Library/ControllerOrder.php';
require_once 'Library/ControllerAdmin.php';
require_once 'Library/Cookie.php';
require_once 'Library/Database.php';
require_once 'Library/Input.php';
require_once 'Library/Action.php';
require_once 'Library/Model.php';
require_once 'Library/Notification.php';
require_once 'Library/Password.php';
require_once 'Library/Session.php';
require_once 'Library/Startup.php';
$startup = new StartUp();