<?php
define('CSRF_TOKEN_EXPIRY', 60 * 30);


define('EXPIRY_CONFIRM_EMAIL_TOKEN_MINUTE', 30);
define('EXPIRY_CONFIRM_EMAIL_TOKEN', 60 * 30);
define('EXPIRY_TWO_FA_TOKEN_MINUTE', 10);
define('EXPIRY_TWO_FA_TOKEN', 60 * 10);
define('EXPIRY_SHORT_TIMEOUT_CAPTCHA', 60 * 10);
define('EXPIRY_LONG_TIMEOUT_CAPTCHA', 60 * 60 * 24);
define('EXPIRY_CANCEL_REGISTER_LINK', 60 * 60 * 24 * 30);
define('EXPIRY_COOKIE_AUTHENTICATION', 60 * 60 * 24 * 7);
define('EXPIRY_SESSION_AUTHENTICATION', 60 * 60 * 6);
define('EXPIRY_FORGOT_PASSWORD_TOKEN_MINUTE', 30);
define('EXPIRY_FORGOT_PASSWORD_TOKEN', 60 * 30);

