<?php
define('EXPIRY_CSRF_TOKEN', 60 * 30);
define('EXPIRY_COOKIE_CART', 60 * 60 * 24 * 7);


define('EXPIRY_TWO_FA_TOKEN', 60 * 10);
define('EXPIRY_TWO_FA_TOKEN_MINUTE', 10);
define('EXPIRY_CONFIRM_EMAIL_TOKEN', 60 * 30);
define('EXPIRY_CONFIRM_EMAIL_TOKEN_MINUTE', 30);
define('EXPIRY_COOKIE_AUTH', 60 * 60 * 24 * 7);
define('EXPIRY_SESSION_AUTH', 60 * 60 * 6);
define('EXPIRY_CANCEL_REGISTER_LINK', 60 * 60 * 24 * 30);
define('TIMEOUT_SHORT_CAPTCHA', 60 * 10);
define('TIMEOUT_LONG_CAPTCHA', 60 * 60 * 24);
define('EXPIRY_RESET_PWD_TOKEN', 60 * 30);
define('EXPIRY_RESET_PWD_TOKEN_MINUTE', 30);