<?php
define('ITEM_LOAD_LIMIT_IN_ONCE', 6);
define('COMMENT_LOAD_LIMIT_IN_ONCE', 6);
define('DETAILS_SIZE_REMAIN_ITEM_LIMIT', 20);
define('PASSWORD_MIN_LIMIT', 8);
define('EMAIL_MAX_LIMIT', 320);
define('EMAIL_MAX_LIMIT_DB', 2560);
define('COMMENT_MAX_LIMIT', 500);
define('COMMENT_MAX_LIMIT_DB', 500);


define('ID_LENGTH', 255);