<?php
define('TR_NOTIFICATION_ERROR_CSRF', 'Beklenmedik bir hata oldu. Lütfen tekrar deneyin.');
define('TR_NOTIFICATION_EMPTY_HIDDEN_INPUT', 'Bir hata oldu. Lütfen tekrar deneyin.');
define('TR_NOTIFICATION_SUCCESS_AUTHENTICATION_KILLED', 'Oturumunuz sonlandırıldı. Lütfen tekrar giriş yapın.');
define('TR_NOTIFICATION_ERROR_DATABASE', 'Beklenmedik bir hata oldu. Lütfen tekrar deneyin.');
define('TR_NOTIFICATION_SUCCESS_LOG_OUT', 'Oturumunuz başarıyla sonlandırıldı.');
// Comment
define('TR_NOTIFICATION_EMPTY_COMMENT', 'Yorum alanı boş olamaz');
define('TR_NOTIFICATION_ERROR_COMMENT_LIMIT', 'Yorum 500 karakterden fazla olamaz');
define('TR_NOTIFICATION_ERROR_COMMENT_CREATE', 'Yorum oluşturulurken bir hata oldu. Lütfen tekrar deneyin.');
define('TR_NOTIFICATION_ERROR_COMMENT_USER_BLOCKED', BRAND . ' hesabınız bloklandığı için yorum yapamazsınız.');
define('TR_NOTIFICATION_SUCCESS_COMMENT_CREATE', 'Yorum başarıyla eklendi. Değerli düşüncelerinizi paylaştığınız için teşekkür ederiz.');
define('TR_NOTIFICATION_ERROR_COMMENT_UPDATE', 'Yorum güncellenirken bir hata oldu. Lütfen tekrar deneyin.');
define('TR_NOTIFICATION_SUCCESS_COMMENT_UPDATE', 'Yorum başarıyla güncellendi');
define('TR_NOTIFICATION_ERROR_COMMENT_DELETE', 'Yorum silinirken bir hata oldu. Lütfen tekrar deneyin.');
define('TR_NOTIFICATION_SUCCESS_COMMENT_DELETE', 'Yorum başarıyla silindi');
define('TR_NOTIFICATION_SUCCESS_COMMENT_APPROVED', 'Yorum herkese görünür olarak güncellendi');
define('TR_NOTIFICATION_SUCCESS_COMMENT_DISAPPROVED', 'Yorum görünmez olarak güncellendi');
// Favorites
define('TR_NOTIFICATION_ERROR_ADD_TO_FAVORITES', 'Ürün favorilere eklenirken bir hata oldu');
define('TR_NOTIFICATION_SUCCESS_ADD_TO_FAVORITES', 'Ürün başarıyla favorilere eklendi');
define('TR_NOTIFICATION_ERROR_REMOVE_FROM_FAVORITES', 'Ürün favorilerden kaldırılırken bir hata oldu');
define('TR_NOTIFICATION_SUCCESS_REMOVE_FROM_FAVORITES', 'Ürün başarıyla favorilerden kaldırıldı');
// Agremments
define('URL_TERMS_TITLE', 'Kullanım Şartları ve Üyelik Sözleşmesi');
define('URL_PRIVACY_TITLE', 'Gizlilik ve Güvenlik Politikası');
define('URL_RETURN_POLICY_TITLE', 'İptal ve İade Koşulları');
// Cart
define('TR_NOTIFICATION_EMPTY_CART_SIZE', 'Sepete eklemeden önce size uygun bedeni seçin');
define('TR_NOTIFICATION_ERROR_ADD_TO_CART', 'Ürün sepete eklenirken bir hata oldu');
define('TR_NOTIFICATION_ERROR_ADD_TO_CART_STOCK_LIMIT', 'Sepetinize stok adedinden fazla ürünü ekleyemezsiniz');
define('TR_NOTIFICATION_ERROR_ADD_TO_CART_FULL', 'Sepetinize tek seferde bir üründen en fazla 10 adet ekleyebilirsiniz');
define('TR_NOTIFICATION_ERROR_ADD_TO_CART_COOKIE_LIMIT', 'Sepete daha fazla ürün ekleyemezsiniz');
define('TR_NOTIFICATION_ERROR_EMPTY_CART', 'Sepet boşaltılırken bir hata oldu');
define('TR_NOTIFICATION_SUCCESS_EMPTY_CART', 'Sepet başarıyla boşaltıldı');
define('TR_NOTIFICATION_ERROR_UPDATE_CART', 'Sepet güncellenirken bir hata oldu');
// Profile
define('URL_PROFILE_INFO_TITLE', 'Profil');
define('URL_PROFILE_ADDRESS_TITLE', 'Adres - Profil');
define('URL_PROFILE_PWD_TITLE', 'Şifre - Profil');
define('URL_PROFILE_EMAIL_TITLE', 'Email - Profil');
define('URL_PROFILE_TEL_TITLE', 'Telefon Numarası - Profil');
define('URL_PROFILE_PHOTO_TITLE', 'Profil Fotoğrafı - Profil');
define('URL_PROFILE_ORDERS_TITLE', 'Siparişlerim - Profil');
// Action
define('TR_NOTIFICATION_ERROR_EMPTY_EMAIL', 'Email adresinizi girin');
define('TR_NOTIFICATION_ERROR_NOT_VALID_EMAIL', 'Geçerli bir email adresi girin');
define('TR_NOTIFICATION_ERROR_NOT_UNIQUE_EMAIL', 'Email adresi zaten kayıtlı. Bilgileriniz ile giriş yapabilirsiniz.');
define('TR_NOTIFICATION_ERROR_EMPTY_PASSWORD', 'Şifrenizi girin');
define('TR_NOTIFICATION_ERROR_NO_WHITE_SPACE_PASSWORD', 'Şifreniz boşluk karakteri içermemelidir');
define('TR_NOTIFICATION_ERROR_MIN_LENGTH_PASSWORD', 'Şifreniz '. PASSWORD_MIN_LIMIT .' karakterden az olamaz');
define('TR_NOTIFICATION_ERROR_PATTERN_PASSWORD', 'Şifreniz en az bir küçük harf, bir büyük harf ve bir rakam içermelidir');
define('TR_NOTIFICATION_ERROR_EMPTY_RE_PASSWORD', 'Şifrenizi tekrar girin');
define('TR_NOTIFICATION_ERROR_NOT_SAME_PASSWORDS', 'Şifreler aynı olmalıdır');
define('TR_NOTIFICATION_ERROR_EMPTY_REGISTER_TERMS', 'Kayıt olabilmek için kullanım şartları ve üyelik sözleşmesi ile gizlilik ve güvenlik politikasını kabul etmelisiniz');
define('TR_NOTIFICATION_ERROR_CAPTCHA_BANNED', 'Ben bir insanım testinde fazla sayıda başarısız oldunuz');
define('TR_NOTIFICATION_ERROR_CAPTCHA_TIMEOUT_1', 'Ben bir insanım testinde başarısız oldunuz. ');
define('TR_NOTIFICATION_ERROR_CAPTCHA_TIMEOUT_2', ' dakika sonra tekrar deneyin.');
define('TR_NOTIFICATION_ERROR_CAPTCHA', 'Ben bir insanım testi başarısız. Lütfen tekrar deneyin.');
define('TR_NOTIFICATION_ERROR_REGISTER', 'Kayıt işlemi gerçekleştirilirken bir hata oldu. Lütfen daha sonra tekrar deneyin.');
define('TR_NOTIFICATION_SUCCESS_REGISTER', 'Kayıt işlemi başarılı. Bilgileriniz ile giriş yapabilirsiniz.');
define('TR_NOTIFICATION_ERROR_REGISTER_CONFIRM_TOKEN_EXPIRIED', 'Email doğrulama kodu zaman aşımına uğradı. Lütfen giriş yaparak tekrar deneyin.');
define('TR_NOTIFICATION_ERROR_EMPTY_REGISTER_CONFIRM_TOKEN', 'Email doğrulama kodunu hatalı girdiniz. Lütfen giriş yaparak tekrar deneyin.');
define('TR_NOTIFICATION_ERROR_REGISTER_CONFIRM', 'Üyeliğiniz aktifleştirilirken bir hata oldu. Lütfen daha sonra giriş yaparak tekrar deneyin.');
define('TR_NOTIFICATION_SUCCESS_REGISTER_CONFIRM', 'Üyeliğiniz başarıyla aktif edildi. Bilgileriniz ile ' . BRAND . ' hesabınıza giriş yapabilirsiniz.');
define('TR_NOTIFICATION_ERROR_REGISTER_CANCEL', 'Üyeliğiniz sonlandırılırken bir hata oldu. Lütfen daha sonra tekrar deneyiniz.');
define('TR_NOTIFICATION_SUCCESS_REGISTER_CANCEL', BRAND . ' üyeliğiniz başarıyla sonlandırıldı.');
define('TR_NOTIFICATION_WARNING_REGISTER_CANCEL', 'Üyeliğinizi daha önce aktifleştirdiğiniz için üyelik iptali yapamazsınız. Ancak daha önce hiç ürün satın almadıysanız; ' . BRAND . ' hesabınızdan, profil sekmesi altında hesabınızı iptal edebilirsiniz.');
define('TR_NOTIFICATION_ERROR_LOGIN', 'Giriş işlemi başarısız. Lütfen tekrar deneyin.');
define('TR_NOTIFICATION_ERROR_FORGOT_PASSWORD_NO_EMAIL', 'Girilen email adresine ait kayıtlı bir ' . BRAND . ' hesabı bulunamadı');
define('TR_NOTIFICATION_ERROR_FORGOT_PASSWORD', 'Şifre sıfırlama işlemi gerçekleştirilirken bir hata oldu. Lütfen daha sonra tekrar deneyiniz.');
define('TR_NOTIFICATION_SUCCESS_FORGOT_PASSWORD', 'Şifre sıfırlama linki email adresinize gönderildi.');
define('TR_NOTIFICATION_SUCCESS_RESET_PASSWORD', 'Şifreniz başarıyla güncellendi. Yeni şifreniz ile giriş yapabilirsiniz.');
define('TR_NOTIFICATION_ERROR_LOGIN_INFORMATIONS', 'Kullanıcı bilgileri yanlış');
define('TR_NOTIFICATION_ERROR_TWO_FA_TOKEN_EXPIRIED', 'İki aşamalı doğrulama kodu zaman aşımına uğradı. Lütfen giriş yaparak tekrar deneyin.');
define('TR_NOTIFICATION_ERROR_EMPTY_TWO_FA_TOKEN', 'İki aşamalı doğrulama kodunu hatalı girdiniz. Lütfen giriş yaparak tekrar deneyin.');
define('TR_NOTIFICATION_ERROR_TWO_FA', 'İki aşamalı doğrulama sırasında bir hata oldu. Lütfen daha sonra giriş yaparak tekrar deneyin.');
// Profile
define('TR_NOTIFICATION_SUCCESS_ACCOUNT_DELETE', BRAND . ' hesabınız başarıyla sonlandırıldı.');
define('TR_NOTIFICATION_ERROR_WRONG_OLD_PASSWORD', 'Güncel şifrenizi hatalı girdiniz');
define('TR_NOTIFICATION_SUCCESS_PROFILE_PASSWORD_UPDATE', 'Şifreniz başarıyla değiştirldi');
define('TR_NOTIFICATION_ERROR_PROFILE_PASSWORD_UPDATE', 'Şifreniz değiştirilirken bir hata oldu. Lütfen daha sonra tekrar deneyin.');
define('TR_NOTIFICATION_ERROR_EMPTY_USER_NAME', 'İsminizi girin');
define('TR_NOTIFICATION_ERROR_EMPTY_USER_LAST_NAME', 'Soy isminizi girin');
define('TR_NOTIFICATION_ERROR_NOT_VALID_USER_NAME', 'İsminiz boşluk karakteri içeremez');
define('TR_NOTIFICATION_ERROR_NOT_VALID_USER_LAST_NAME', 'Soy isminiz boşluk karakteri içeremez');
define('TR_NOTIFICATION_ERROR_MAX_LIMIT_USER_NAME', 'İsminiz karakter sınırını geçmemelidir');
define('TR_NOTIFICATION_ERROR_MAX_LIMIT_USER_LAST_NAME', 'Soy isminiz karakter sınırını geçmemelidir');
define('TR_NOTIFICATION_SUCCESS_PROFILE_USER_NAME_UPDATE', 'İsminiz başarıyla güncellendi');
define('TR_NOTIFICATION_ERROR_NEW_USER_NAME', 'Yeni isminizi girin');
define('TR_NOTIFICATION_ERROR_PROFILE_NOT_UNIQUE_EMAIL', 'Email adresi zaten kayıtlı');
define('TR_NOTIFICATION_ERROR_PROFILE_NEW_EMAIL', 'Yeni email adresinizi girin');
define('TR_NOTIFICATION_ERROR_EMAIL_UPDATE', 'Email adresiniz güncellenirken bir hata oldu. Lütfen daha sonra tekrar deneyin.');
define('TR_NOTIFICATION_ERROR_EMPTY_PHONE', 'Telefon numaranızı girin');
define('TR_NOTIFICATION_ERROR_NOT_VALID_PHONE', 'Girdiğiniz telefon numarası geçerli değil');
define('TR_NOTIFICATION_ERROR_EMPTY_EMAIL_UPDATE_TOKEN', 'Email doğrulama kodunu hatalı girdiniz. Lütfen tekrar deneyin.');
define('TR_NOTIFICATION_ERROR_EMAIL_UPDATE_TOKEN_EXPIRIED', 'Email doğrulama kodu zaman aşımına uğradı. Lütfen tekrar deneyin.');
define('TR_NOTIFICATION_SUCCESS_EMAIL_UPDATE', 'Email adresiniz başarıyla değiştirildi');
define('TR_NOTIFICATION_SUCCESS_PROFILE_PHOTO_UPDATE', 'Profil fotoğrafı başarıyla değiştirildi');
define('TR_NOTIFICATION_ERROR_PROFILE_PHOTO_UPDATE', 'Profil fotoğrafınızı yükleyin');
define('TR_NOTIFICATION_ERROR_LIMIT_PROFILE_PHOTO_UPDATE', 'Profil fotoğrafınızın boyutu 1 MB dan fazla olmamalıdır');
define('TR_NOTIFICATION_ERROR_IDK_PROFILE_PHOTO_UPDATE', 'Profil fotoğrafınız değiştirilirken bir hata oldu. Lütfen daha sonra tekrar deneyiniz.');
define('TR_NOTIFICATION_ERROR_EXTENSION_PROFILE_PHOTO_UPDATE', 'Profil fotoğrafınızın uzantısı jpeg veya png olmamalıdır');
define('TR_NOTIFICATION_ERROR_NEW_PHONE_NUMBER', 'Yeni telefon numaranızı girin');
define('TR_NOTIFICATION_SUCCESS_PROFILE_PHONE_NUMBER_UPDATE', 'Telefon numaranız başarıyla güncellendi');
define('TR_NOTIFICATION_ERROR_EMPTY_CITY', 'Şehir boş olamaz');
define('TR_NOTIFICATION_ERROR_NOT_VALID_CITY', 'Geçerli bir şehir girin');
define('TR_NOTIFICATION_ERROR_EMPTY_COUNTY', 'İlçe boş olamaz');
define('TR_NOTIFICATION_ERROR_NOT_VALID_COUNTY', 'Geçerli bir ilçe girin');
define('TR_NOTIFICATION_ERROR_EMPTY_NEIGHBORHOOD', 'Mahalle boş olamaz');
define('TR_NOTIFICATION_ERROR_NOT_VALID_NEIGHBORHOOD', 'Geçerli bir mahalle girin');
define('TR_NOTIFICATION_ERROR_EMPTY_STREET', 'Sokak boş olamaz');
define('TR_NOTIFICATION_ERROR_NOT_VALID_STREET', 'Geçerli bir Sokak girin');
define('TR_NOTIFICATION_ERROR_EMPTY_BUILDING_NO', 'Apartman Numarası boş olamaz');
define('TR_NOTIFICATION_ERROR_NOT_VALID_BUILDING_NO', 'Geçerli bir apartman numarası girin');
define('TR_NOTIFICATION_ERROR_EMPTY_APARTMENT_NO', 'Daire Numarası boş olamaz');
define('TR_NOTIFICATION_ERROR_NOT_VALID_APARTMENT_NO', 'Geçerli bir daire numarası girin');
define('TR_NOTIFICATION_ERROR_EMPTY_ZIP_NO', 'ZİP Numarası boş olamaz');
define('TR_NOTIFICATION_ERROR_NOT_VALID_ZIP_NO', 'Geçerli bir zip numarası girin');
define('TR_NOTIFICATION_ERROR_CREATE_ADDRESS_LIMIT', 'En fazla 5 adet adres ekleyebilirsiniz');
define('TR_NOTIFICATION_ERROR_CREATE_ADDRESS', 'Adres oluşturulurken bir hata oldu. Lütfen daha sonra tekrar deneyin.');
define('TR_NOTIFICATION_SUCCESS_CREATE_ADDRESS', 'Adres başarıyla oluşturuldu');
define('TR_NOTIFICATION_ERROR_UPDATE_ADDRESS', 'Adres güncellenirken bir hata oldu. Lütfen daha sonra tekrar deneyin.');
define('TR_NOTIFICATION_SUCCESS_UPDATE_ADDRESS', 'Adres başarıyla güncellendi');
define('TR_NOTIFICATION_ERROR_DELETE_ADDRESS', 'Adres silinirken bir hata oldu. Lütfen daha sonra tekrar deneyin.');
define('TR_NOTIFICATION_SUCCESS_DELETE_ADDRESS', 'Adres başarıyla silindi');
define('TR_NOTIFICATION_ERROR_COMMENT_USER_EMPTY_NAME', 'Yorum eklemeden önce profilinizden isminizi eklemelisiniz');
define('TR_NOTIFICATION_SUCCESS_PROFILE_2FA_DEACTIVE', '2 aşamalı doğrulama devre dışı bırakıldı');
define('TR_NOTIFICATION_SUCCESS_PROFILE_2FA_ACTIVE', '2 aşamalı doğrulama aktif edildi');